import { Router } from 'express';
import { ai } from '../ai';
import { Storage } from '../storage';

export const voiceRouter = Router();

// Text to Speech endpoint using gemini-3.8-flash-lite-tts
voiceRouter.post('/tts', async (req, res) => {
  try {
    const { text, voiceName } = req.body;
    if (!text || typeof text !== 'string') {
      return res.status(400).json({ error: 'Text prompt is required for TTS' });
    }

    const settings = Storage.getSettings();
    const selectedVoice = voiceName || settings.voiceName || 'Kore';

    // Truncate text if excessively long for TTS audio synthesis (first 600 characters or clean excerpt)
    const cleanText = text
      .replace(/```[\s\S]*?```/g, ' [code block omitted] ')
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      .replace(/[#*_`]/g, '')
      .slice(0, 800)
      .trim();

    if (!cleanText) {
      return res.status(400).json({ error: 'No speakable text found' });
    }

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash-lite-tts',
      contents: [
        {
          role: 'user',
          parts: [
            {
              text: cleanText,
            },
          ],
        },
      ],
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: selectedVoice },
          },
        },
      },
    });

    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!base64Audio) {
      return res.status(500).json({ error: 'No audio generated by TTS model' });
    }

    // Unary default returns complete WAV file audio/wav
    return res.json({
      audioUrl: `data:audio/wav;base64,${base64Audio}`,
      voice: selectedVoice,
      textLength: cleanText.length,
    });
  } catch (error: any) {
    console.error('TTS error:', error);
    res.status(500).json({ error: error.message || 'Failed to synthesize speech' });
  }
});

// Audio Transcription endpoint using gemini-3.5-transcribe
voiceRouter.post('/transcribe', async (req, res) => {
  try {
    const { audioData, mimeType = 'audio/webm' } = req.body;
    if (!audioData) {
      return res.status(400).json({ error: 'audioData base64 is required' });
    }

    // Clean base64 string
    const base64Clean = audioData.replace(/^data:[a-zA-Z0-9\/\-]+;base64,/, '');

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-transcribe',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType,
              data: base64Clean,
            },
          },
          {
            text: 'Transcribe this speech accurately. Return only the transcribed text without extra preamble.',
          },
        ],
      },
    });

    const transcribed = response.text?.trim() || '';
    return res.json({ text: transcribed });
  } catch (error: any) {
    console.error('Transcription error:', error);
    res.status(500).json({ error: error.message || 'Audio transcription failed' });
  }
});
